//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSmart.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullyJoinedShoppingList
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool Main { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int CategorySort { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public string ShopListTitle { get; set; }
        public System.DateTime ShopListDate { get; set; }
        public int ShopListId { get; set; }
        public string SuperMarketName { get; set; }
        public int SuperMarketId { get; set; }
        public string CustomerUserName { get; set; }
        public int CustomerId { get; set; }
    }
}
