//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSmart.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullyJoinedProduct
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool Main { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int CategorySort { get; set; }
        public string SuperMarketName { get; set; }
        public int SuperMarketId { get; set; }
    }
}
